######################################################################
# Automatically generated by qmake (2.01a) Mon Mar 16 13:52:26 2015
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += calculator.h
SOURCES += calculator.cpp main.cpp
